# Generated by Django 3.2.5 on 2021-08-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=18, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pattern', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Starred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stock_symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('date', models.CharField(blank=True, max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
